{
 "title": "Short Url Metrics",
 "time": { "from": "2025-07-08T15:50:38.459Z", "to": "2025-07-08T15:59:25.121Z" },
 "panels": [
  {
   "title": "Latency P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(shorturl_http_server_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(shorturl_http_server_request_duration_seconds_sum[5m]) / rate(shorturl_http_server_request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Hits Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(shorturl_shorturl_endpoint_total) by (service, endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(shorturl_shorturl_redirect_total) by (shortUrl))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}